apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agent-sentry-issue-analyzer
  namespace: '{{ "NAMESPACE" | env }}'
data:
  SENTRY_DSN: '{{ "SENTRY_DSN_KEY" | env | teamvaultUrl | base64 }}'
  ANTHROPIC_AUTH_TOKEN: '{{ "MOPmQL" | teamvaultPassword | base64 }}'
