apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-claude
  namespace: '{{ "NAMESPACE" | env }}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
