// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent-sentry-issue-analyzer/pkg/fixagent"
)

type TraceReader struct {
	HasFirstPartyFrameStub        func(context.Context, string) (bool, error)
	hasFirstPartyFrameMutex       sync.RWMutex
	hasFirstPartyFrameArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	hasFirstPartyFrameReturns struct {
		result1 bool
		result2 error
	}
	hasFirstPartyFrameReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TraceReader) HasFirstPartyFrame(arg1 context.Context, arg2 string) (bool, error) {
	fake.hasFirstPartyFrameMutex.Lock()
	ret, specificReturn := fake.hasFirstPartyFrameReturnsOnCall[len(fake.hasFirstPartyFrameArgsForCall)]
	fake.hasFirstPartyFrameArgsForCall = append(fake.hasFirstPartyFrameArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.HasFirstPartyFrameStub
	fakeReturns := fake.hasFirstPartyFrameReturns
	fake.recordInvocation("HasFirstPartyFrame", []interface{}{arg1, arg2})
	fake.hasFirstPartyFrameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TraceReader) HasFirstPartyFrameCallCount() int {
	fake.hasFirstPartyFrameMutex.RLock()
	defer fake.hasFirstPartyFrameMutex.RUnlock()
	return len(fake.hasFirstPartyFrameArgsForCall)
}

func (fake *TraceReader) HasFirstPartyFrameCalls(stub func(context.Context, string) (bool, error)) {
	fake.hasFirstPartyFrameMutex.Lock()
	defer fake.hasFirstPartyFrameMutex.Unlock()
	fake.HasFirstPartyFrameStub = stub
}

func (fake *TraceReader) HasFirstPartyFrameArgsForCall(i int) (context.Context, string) {
	fake.hasFirstPartyFrameMutex.RLock()
	defer fake.hasFirstPartyFrameMutex.RUnlock()
	argsForCall := fake.hasFirstPartyFrameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TraceReader) HasFirstPartyFrameReturns(result1 bool, result2 error) {
	fake.hasFirstPartyFrameMutex.Lock()
	defer fake.hasFirstPartyFrameMutex.Unlock()
	fake.HasFirstPartyFrameStub = nil
	fake.hasFirstPartyFrameReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *TraceReader) HasFirstPartyFrameReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasFirstPartyFrameMutex.Lock()
	defer fake.hasFirstPartyFrameMutex.Unlock()
	fake.HasFirstPartyFrameStub = nil
	if fake.hasFirstPartyFrameReturnsOnCall == nil {
		fake.hasFirstPartyFrameReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasFirstPartyFrameReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *TraceReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TraceReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fixagent.TraceReader = new(TraceReader)
