// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent-sentry-issue-analyzer/pkg/verdict"
)

type DisqualifierEvaluator struct {
	EvaluateStub        func(context.Context, verdict.DisqualifierInput) ([]verdict.Disqualifier, error)
	evaluateMutex       sync.RWMutex
	evaluateArgsForCall []struct {
		arg1 context.Context
		arg2 verdict.DisqualifierInput
	}
	evaluateReturns struct {
		result1 []verdict.Disqualifier
		result2 error
	}
	evaluateReturnsOnCall map[int]struct {
		result1 []verdict.Disqualifier
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DisqualifierEvaluator) Evaluate(arg1 context.Context, arg2 verdict.DisqualifierInput) ([]verdict.Disqualifier, error) {
	fake.evaluateMutex.Lock()
	ret, specificReturn := fake.evaluateReturnsOnCall[len(fake.evaluateArgsForCall)]
	fake.evaluateArgsForCall = append(fake.evaluateArgsForCall, struct {
		arg1 context.Context
		arg2 verdict.DisqualifierInput
	}{arg1, arg2})
	stub := fake.EvaluateStub
	fakeReturns := fake.evaluateReturns
	fake.recordInvocation("Evaluate", []interface{}{arg1, arg2})
	fake.evaluateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DisqualifierEvaluator) EvaluateCallCount() int {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return len(fake.evaluateArgsForCall)
}

func (fake *DisqualifierEvaluator) EvaluateCalls(stub func(context.Context, verdict.DisqualifierInput) ([]verdict.Disqualifier, error)) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = stub
}

func (fake *DisqualifierEvaluator) EvaluateArgsForCall(i int) (context.Context, verdict.DisqualifierInput) {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	argsForCall := fake.evaluateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DisqualifierEvaluator) EvaluateReturns(result1 []verdict.Disqualifier, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	fake.evaluateReturns = struct {
		result1 []verdict.Disqualifier
		result2 error
	}{result1, result2}
}

func (fake *DisqualifierEvaluator) EvaluateReturnsOnCall(i int, result1 []verdict.Disqualifier, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	if fake.evaluateReturnsOnCall == nil {
		fake.evaluateReturnsOnCall = make(map[int]struct {
			result1 []verdict.Disqualifier
			result2 error
		})
	}
	fake.evaluateReturnsOnCall[i] = struct {
		result1 []verdict.Disqualifier
		result2 error
	}{result1, result2}
}

func (fake *DisqualifierEvaluator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DisqualifierEvaluator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ verdict.DisqualifierEvaluator = new(DisqualifierEvaluator)
